apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv-tamer
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0ac77c6d7ade4bff3
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc-tamer
  namespace: tamer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi



