apiVersion: v1
kind: PersistentVolume
metadata:
  name: tamer-alertmanager-new
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0e5aab99871a36af7
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tamer-alertmanager-new
  namespace: tamer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
