apiVersion: v1
kind: PersistentVolume
metadata:
  name: tamer-prometheus-new
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0f9e5ef0a06a1588c
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tamer-prometheus-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
