alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "manual"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    volumeClaimTemplates:
    - metadata:
        name: alertmanager-pvc-tamer
      spec:
        storageClassName: "manual"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "manual"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi

grafana:
  persistence:
    enabled: true
    storageClassName: "manual"
    accessModes:
      - ReadWriteOnce
    size: 15Gi
    finalizers:
      - kubernetes.io/pvc-protection

nodeExporter:
  enabled: true
  service:
    type: ClusterIP
    port: 9100

kubeStateMetrics:
  enabled: true
