nodeExporter:
  enabled: true
  service:
    type: ClusterIP
    port: 9100

kubeStateMetrics:
  enabled: true

replicaCount: 1

server:
  persistentVolume:
    enabled: true
    existingClaim: tamer-prometheus-new
    storageClass: gp2
    size: 15Gi

alertmanager:
  enabled: true
  persistence:
    enabled: true
    existingClaim: tamer-alertmanager-new
    size: 2Gi
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
