apiVersion: v1
kind: PersistentVolume
metadata:
  name: tamer-sonar-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-08c1435c3aea88c38
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ptamer-sonar-pv
  namespace: tamer
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
