apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: yolo5 # {{ .Values.app }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: yolo5-deployment
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50