apiVersion: v1
kind: Service
metadata:  
  name: yolo5-service
spec:
  selector:    
    app: yolo5 # {{ .Values.app }}
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP