apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-tamer
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-05e283658274a8b1a
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-tamer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi