apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-tamer
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-03c653c86340b548e
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-tamer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi