apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      serviceAccountName: yolov5-sa
      terminationGracePeriodSeconds: 30
      containers:
      - name: polybot
        image: tamer153/polybot-k8s:1.0.7
        ports:
        - containerPort: 8443
        env:
        - name: bucket
          value: tamerawsbucket
        - name: queue_url
          value: https://sqs.us-east-1.amazonaws.com/933060838752/tamer-sqs
        - name: telegram_chat_url
          value: tamer.atech-bot.click
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8443
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8443
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443


---

apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
 name: yolov5-sa
 namespace: tamer
 annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::933060838752:role/tamer-eks-sqs-fullaccess