{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polybot.serviceAccountName" . }}
  labels:
    {{- include "polybot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---

apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
 name: yolov5-sa
 namespace: tamer
 annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::933060838752:role/tamer-eks-sqs-fullaccess
